name: Full-Repo Scan Test - sshedge

on:
  push:
  workflow_dispatch:

jobs:
  full-scan:
    name: Run Full-Repo Copyright and License Scan
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@test_copyright_license_action
    with:
      enable-semgrep-scan: false
      enable-dependency-review: false
      enable-repolinter-check: false
      enable-copyright-license-check: false
      enable-commit-email-check: false
      enable-commit-msg-check: false
      enable-armor-checkers: false
      enable-full-repo-scan: true
    permissions:
      contents: read
      security-events: write
