name: Tets QC Preflight Checks - sshedge

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  preflight:
    name: Run QC Preflight Checks
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@test_repo_policy_actions
    with:
      enable-semgrep-scan: false
      enable-dependency-review: false
      enable-repolinter-check: true
      enable-repo-policy-check: true
      enable-copyright-license-check: true
      enable-commit-email-check: false
      enable-commit-msg-check: false
      enable-armor-checkers: false

    permissions:
      contents: read
      security-events: write